# Generated by Django 5.2 on 2025-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='agency_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='agency_temporary_staffing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='asylum_seeker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='blue_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='city_part',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='civil_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='display_information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='district',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='education',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='employee_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='freelance_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='full_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='min_wage_hourly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='min_wage_monthly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='municipality',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='non_eu_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='part_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='profession',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='region',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='shifts',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='short_term_employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='text_to_search',
            field=models.TextField(blank=True, null=True),
        ),
    ]
